<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\CourseController;
use App\Controllers\CourseSubjectController;
use App\Controllers\CourseViewController;
use App\Controllers\DashboardController;
use App\Controllers\GradeController;
use App\Controllers\ReportBuilderController;
use App\Controllers\ReportController;
use App\Controllers\StudentController;
use App\Controllers\SubjectController;
use App\Controllers\TeacherAssignmentController;
use App\Controllers\TeacherDashboardController;
use App\Controllers\UserController;

$router->get('/', [AuthController::class, 'showLogin']);
$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/logout', [AuthController::class, 'logout']);
$router->get('/dashboard', [DashboardController::class, 'index']);
$router->get('/dashboard/inicial', [DashboardController::class, 'inicial']);
$router->get('/dashboard/primaria', [DashboardController::class, 'primaria']);
$router->get('/dashboard/secundaria', [DashboardController::class, 'secundaria']);
$router->get('/docente/dashboard', [TeacherDashboardController::class, 'index']);
$router->get('/docente/notas', [GradeController::class, 'index']);
$router->post('/docente/notas/store', [GradeController::class, 'store']);
$router->get('/cursos', [CourseController::class, 'index']);
$router->get('/cursos/create', [CourseController::class, 'create']);
$router->post('/cursos/store', [CourseController::class, 'store']);
$router->get('/cursos/edit', [CourseController::class, 'edit']);
$router->post('/cursos/update', [CourseController::class, 'update']);
$router->post('/cursos/status', [CourseController::class, 'status']);
$router->get('/materias', [SubjectController::class, 'index']);
$router->get('/materias/create', [SubjectController::class, 'create']);
$router->post('/materias/store', [SubjectController::class, 'store']);
$router->get('/materias/edit', [SubjectController::class, 'edit']);
$router->post('/materias/update', [SubjectController::class, 'update']);
$router->post('/materias/status', [SubjectController::class, 'status']);
$router->get('/cursos-materias', [CourseSubjectController::class, 'index']);
$router->get('/cursos-materias/create', [CourseSubjectController::class, 'create']);
$router->post('/cursos-materias/store', [CourseSubjectController::class, 'store']);
$router->get('/cursos-materias/edit', [CourseSubjectController::class, 'edit']);
$router->post('/cursos-materias/update', [CourseSubjectController::class, 'update']);
$router->post('/cursos-materias/status', [CourseSubjectController::class, 'status']);
$router->get('/ver-curso', [CourseViewController::class, 'show']);
$router->get('/boletin', [ReportController::class, 'boletin']);
$router->get('/reportes', [ReportBuilderController::class, 'index']);
$router->get('/reportes/constructor', [ReportBuilderController::class, 'constructor']);
$router->post('/reportes/constructor', [ReportBuilderController::class, 'constructor']);
$router->get('/reportes/ver', [ReportBuilderController::class, 'ver']);
$router->get('/reportes/eliminar', [ReportBuilderController::class, 'delete']);
$router->get('/docentes-asignaciones', [TeacherAssignmentController::class, 'index']);
$router->get('/docentes-asignaciones/create', [TeacherAssignmentController::class, 'create']);
$router->post('/docentes-asignaciones/store', [TeacherAssignmentController::class, 'store']);
$router->get('/docentes-asignaciones/edit', [TeacherAssignmentController::class, 'edit']);
$router->post('/docentes-asignaciones/update', [TeacherAssignmentController::class, 'update']);
$router->post('/docentes-asignaciones/status', [TeacherAssignmentController::class, 'status']);
$router->get('/estudiantes', [StudentController::class, 'index']);
$router->get('/estudiantes/create', [StudentController::class, 'create']);
$router->post('/estudiantes/store', [StudentController::class, 'store']);
$router->get('/estudiantes/show', [StudentController::class, 'show']);
$router->get('/estudiantes/edit', [StudentController::class, 'edit']);
$router->post('/estudiantes/update', [StudentController::class, 'update']);
$router->post('/estudiantes/delete', [StudentController::class, 'delete']);
$router->get('/usuarios', [UserController::class, 'index']);
$router->get('/usuarios/create', [UserController::class, 'create']);
$router->post('/usuarios/store', [UserController::class, 'store']);
$router->get('/usuarios/edit', [UserController::class, 'edit']);
$router->post('/usuarios/update', [UserController::class, 'update']);
$router->post('/usuarios/status', [UserController::class, 'toggleStatus']);
